### ISSUE TITLE
Tracking issue for release

### ISSUE THREAD

**Issue by museun** [museun/json_to_rust#1]
- [ ] UI Tests
- [x] Flags
    - [x] field naming scheme
    - [x] struct naming scheme
    - [x] collapse `Option<Vec<T>>` into `Vec<T>`
    - [ ] ~prefer modules instead of renaming~
    - [x] use specific map/vec implementations
    - [x] which standard derives to use
    - [x] `#[serde(default)]`
